addSbtPlugin("org.typelevel" %% "sbt-catalysts" % "0.34")
addSbtPlugin("de.heikoseeberger" % "sbt-header" % "5.3.1")
addSbtPlugin("com.github.tkawachi" % "sbt-doctest" % "0.9.5")
addSbtPlugin("com.47deg" % "sbt-microsites" % "1.0.2")
addSbtPlugin("org.scalameta" % "sbt-mdoc" % "2.1.0")
